"""
Type stubs for the pyiks module.
"""

class BadXmlError(Exception): ...
class BadJidError(Exception): ...
class XmppError(Exception): ...

class PyDocumentChildren:
    def __iter__(self) -> PyDocumentChildren: ...
    def __next__(self) -> Document: ...

class Document:
    def __init__(self, name: str) -> None: ...
    def insert_tag(self, tag: str) -> Document: ...
    def append_tag(self, tag: str) -> Document: ...
    def prepend_tag(self, tag: str) -> Document: ...
    def insert_cdata(self, cdata: str) -> Document: ...
    def append_cdata(self, cdata: str) -> Document: ...
    def prepend_cdata(self, cdata: str) -> Document: ...
    def insert_attribute(self, name: str, value: str) -> Document: ...
    def set_attribute(self, name: str, value: str | None) -> Document: ...
    def remove(self) -> None: ...
    def next(self) -> Document: ...
    def next_tag(self) -> Document: ...
    def previous(self) -> Document: ...
    def previous_tag(self) -> Document: ...
    def parent(self) -> Document: ...
    def root(self) -> Document: ...
    def first_child(self) -> Document: ...
    def last_child(self) -> Document: ...
    def first_tag(self) -> Document: ...
    def find_tag(self, tag: str) -> Document: ...
    def __iter__(self) -> PyDocumentChildren: ...
    def is_null(self) -> bool: ...
    def is_tag(self) -> bool: ...
    def name(self) -> str: ...
    def attribute(self, name: str) -> str | None: ...
    def attributes(self) -> list[tuple[str, str]]: ...
    def cdata(self) -> str: ...
    def __str__(self) -> str: ...

class XmppClient:
    def __init__(
        self,
        jid: str,
        password: str,
        debug: bool = ...,
        server: str | None = ...,
    ) -> None: ...
    def wait_for_stanza(self) -> Document: ...
    def send_stanza(self, stanza: Document) -> None: ...
    def request_roster(self) -> None: ...
    def send_message(self, to: str, body: str) -> None: ...

def parse(xml_text: str | bytes) -> Document: ...
